apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app-blue
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fitness-app
      version: blue
  template:
    metadata:
      labels:
        app: fitness-app
        version: blue
    spec:
      containers:
        - name: fitness-app-container
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080

