apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app-deployment
spec:
  replicas: 4 # You can change this number
  strategy:
    type: RollingUpdate # This is the default, but good to be explicit
    rollingUpdate:
      maxSurge: 1       # Create 1 new pod at a time
      maxUnavailable: 1 # Take down 1 old pod at a time
  selector:
    matchLabels:
      app: fitness-app
  template:
    metadata:
      labels:
        app: fitness-app
        version: v1
    spec:
      containers:
      - name: fitness-app-container
        # Use the image name from your Jenkinsfile
        image: chetanmatadmtech/fitness-app:v1 
        ports:
        # Use the port from your Dockerfile
        - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-app-service
spec:
  # NodePort makes it accessible via 'minikube service'
  type: NodePort 
  selector:
    # This must match the 'app' label in the Deployment's template
    app: fitness-app 
  ports:
  - protocol: TCP
    port: 8080       # Port inside the cluster
    targetPort: 8080 # Port on the pod
