apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app-green
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fitness-app
      version: VERSION_PLACEHOLDER   # Dynamic version label
  template:
    metadata:
      labels:
        app: fitness-app
        version: VERSION_PLACEHOLDER   # Dynamic version label
    spec:
      containers:
      - name: fitness-app-container
        image: IMAGE_PLACEHOLDER       # Dynamic image
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20

