apiVersion: v1
kind: Service
metadata:
  name: fitness-app-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: fitness-app
    version: VERSION_PLACEHOLDER   # Jenkins will replace this dynamically

