apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app-canary
  namespace: fitness
spec:
  replicas: 1  # Small fraction
  selector:
    matchLabels:
      app: fitness-app
      version: canary
  template:
    metadata:
      labels:
        app: fitness-app
        version: canary
    spec:
      containers:
      - name: fitness-app
        image: chetanmatadmtech/fitness-app:v2
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20

