apiVersion: v1
kind: Service
metadata:
  name: fitness-service-a
  namespace: fitness
spec:
  selector:
    version: a
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-service-b
  namespace: fitness
spec:
  selector:
    version: b
  ports:
  - port: 80
    targetPort: 8080

