apiVersion: v1
kind: Service
metadata:
  name: fitness-app-service
  namespace: fitness
spec:
  type: ClusterIP
  selector:
    app: fitness-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

